### ISSUE TITLE
상세화면 UI 수정사항

### ISSUE THREAD

**Issue by jsh9611** [DeveloperAcademy-POSTECH/MC3-Team6-UDD#47]
- [x] tabBar safeArea 고려하기
- [x] 네비게이션 타이틀 고려하기
- [ ] 이미지 추가하기
- [x] 하단에 버튼 UI 변경
- [x] 신고하기 버튼 삭제
- [x] 더미 삭제

**Comment by minjae9610** [comment]
이슈 및 PR Assignees, Labels, Project, Milestone 채워주세요

**Comment by jsh9611** [comment]
@minjae9610 깜빡했네요. 
추가 감사합니다!
